apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zitadel-db
  namespace: skymap
spec:
  serviceName: zitadel-db
  replicas: 1
  selector:
    matchLabels:
      app: zitadel-db
  template:
    metadata:
      labels:
        app: zitadel-db
    spec:
      containers:
        - name: zitadel-db
          image: cr.yandex/crpvlpmjteb6egojpc4g/postgres:16-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: skymap-secrets
                  key: ZITADEL_DB_PASSWORD
            - name: POSTGRES_DB
              value: zitadel
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: zitadel-db-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U postgres -d zitadel"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U postgres -d zitadel"]
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 256Mi
  volumeClaimTemplates:
    - metadata:
        name: zitadel-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
