"""add star_catalog and star_aliases tables

Revision ID: c2ff37466c44
Revises: d8d4e8fc687f
Create Date: 2026-03-22 19:46:26.285926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2ff37466c44'
down_revision: Union[str, Sequence[str], None] = 'd8d4e8fc687f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('star_catalog',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('proper_name', sa.String(), nullable=True),
    sa.Column('hip_id', sa.Integer(), nullable=True),
    sa.Column('hd_id', sa.Integer(), nullable=True),
    sa.Column('hr_id', sa.Integer(), nullable=True),
    sa.Column('sao_id', sa.Integer(), nullable=True),
    sa.Column('tyc_id', sa.String(), nullable=True),
    sa.Column('bd_id', sa.String(), nullable=True),
    sa.Column('gcrv_id', sa.Integer(), nullable=True),
    sa.Column('bayer', sa.String(), nullable=True),
    sa.Column('flamsteed', sa.String(), nullable=True),
    sa.Column('constellation', sa.String(), nullable=True),
    sa.Column('ra', sa.Float(), nullable=True),
    sa.Column('dec', sa.Float(), nullable=True),
    sa.Column('parallax', sa.Float(), nullable=True),
    sa.Column('distance_ly', sa.Float(), nullable=True),
    sa.Column('pm_ra', sa.Float(), nullable=True),
    sa.Column('pm_dec', sa.Float(), nullable=True),
    sa.Column('radial_velocity', sa.Float(), nullable=True),
    sa.Column('mag_v', sa.Float(), nullable=True),
    sa.Column('mag_b', sa.Float(), nullable=True),
    sa.Column('mag_g', sa.Float(), nullable=True),
    sa.Column('mag_bp', sa.Float(), nullable=True),
    sa.Column('mag_rp', sa.Float(), nullable=True),
    sa.Column('abs_mag', sa.Float(), nullable=True),
    sa.Column('color_bv', sa.Float(), nullable=True),
    sa.Column('spectral_type', sa.String(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('luminosity', sa.Float(), nullable=True),
    sa.Column('mass', sa.Float(), nullable=True),
    sa.Column('radius', sa.Float(), nullable=True),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('variability_type', sa.String(), nullable=True),
    sa.Column('variability_period', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_index(op.f('ix_star_catalog_hip_id'), 'star_catalog', ['hip_id'], unique=False)
    op.create_index(op.f('ix_star_catalog_proper_name'), 'star_catalog', ['proper_name'], unique=False)
    op.create_table('star_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('catalog', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['star_catalog.source_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_star_aliases_alias'), 'star_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_star_aliases_source_id'), 'star_aliases', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_star_aliases_source_id'), table_name='star_aliases')
    op.drop_index(op.f('ix_star_aliases_alias'), table_name='star_aliases')
    op.drop_table('star_aliases')
    op.drop_index(op.f('ix_star_catalog_proper_name'), table_name='star_catalog')
    op.drop_index(op.f('ix_star_catalog_hip_id'), table_name='star_catalog')
    op.drop_table('star_catalog')
    # ### end Alembic commands ###
