apiVersion: apps/v1
kind: Deployment
metadata:
  name: solver-api
  namespace: skymap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solver-api
  template:
    metadata:
      labels:
        app: solver-api
    spec:
      containers:
        - name: solver-api
          image: cr.yandex/crpvlpmjteb6egojpc4g/skymap-solver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: skymap-config
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: skymap-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: skymap-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: skymap-secrets
                  key: POSTGRES_DB
            - name: DATABASE_URL
              value: "postgresql+asyncpg://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: skymap-secrets
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: skymap-secrets
                  key: MINIO_SECRET_KEY
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 30
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 512Mi
